### ISSUE TITLE
Max supported fontSize

### ISSUE THREAD

**Issue by tommitrov** [anday013/react-native-otp-entry#1]
![20230821_152744](https://github.com/anday013/react-native-otp-entry/assets/135219537/98387b5f-0b2b-49d4-a9c1-1f36de423c4a)

What is the maximum supported fontSize for OTP inputs?
With fontSize: 46, the inputs are like cut on the top. Can you please propose solution for this issue?

**Comment by anday013** [comment]
@tommitrov Thank you for bringing this up! I'll definitely look into it in the upcoming days

**Comment by anday013** [comment]
@tommitrov Fixed. Please try to update to the latest version 🙂
