### ISSUE TITLE
While trying to resolve module `react-native-otp-entry` from file

### ISSUE THREAD

**Issue by programmergp** [anday013/react-native-otp-entry#14]
i have this issues ussing expo: 
While trying to resolve module `react-native-otp-entry` from file `/Users/expo/workingdir/build/screens/login/TwoFA.js`, the package `/Users/expo/workingdir/build/node_modules/react-native-otp-entry/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/expo/workingdir/build/node_modules/react-native-otp-entry/dist/index.js`. Indeed, none of these files exist:

  * /Users/expo/workingdir/build/node_modules/react-native-otp-entry/dist/index.js(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  * /Users/expo/workingdir/build/node_modules/react-native-otp-entry/dist/index.js/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
Learn more: https://docs.expo.dev/build-reference/troubleshooting
can you help me on this

**Comment by anday013** [comment]
Hi @programmergp , I replicated the issue, it's definitely a bug in the latest version. I am working on it. Thank you for bringing it up!

**Comment by anday013** [comment]
@programmergp done, fixed. Please try to update to the latest version (v1.1.9) :)
