### ISSUE TITLE
Focus colour is not working 

### ISSUE THREAD

**Issue by KamranBarlas111** [anday013/react-native-otp-entry#16]
@anday013  There is an issue in the library. I just created the sample app and found that the **focusColor** prop doesn't work when I use the **borderColor** in the **pinCodeContainerStyle** theme prop.

Here I attached the screenshots to explain the issue
![Working-Fine](https://github.com/anday013/react-native-otp-entry/assets/105642319/99ea8da8-e70b-45e5-aa3d-ec77136b1f13)
![Focus-Not-Working](https://github.com/anday013/react-native-otp-entry/assets/105642319/7890bb94-d9a1-47c6-adb9-8d90d3988a27)

**Comment by anday013** [comment]
Hi @KamranBarlas111 , I see the problem. Thank you for bringing it up. I'm preparing a fix :)

**Comment by KamranBarlas111** [comment]
@anday013 Thank You So Much. It's working fine now
