### ISSUE TITLE
Need to style the focused input container

### ISSUE THREAD

**Issue by AbdElRahmanMostafa1** [anday013/react-native-otp-entry#19]
Here is the active input which holds number 4

Need to access all styling property for the active input

![image](https://github.com/anday013/react-native-otp-entry/assets/68715550/89f5c843-6184-4dc7-aae7-202908e94b26)

**Comment by anday013** [comment]
@AbdElRahmanMostafa1 Thank you for bringing it up and for PR. I'll take a look at it soon :)

**Comment by anday013** [comment]
@AbdElRahmanMostafa1 Done merged. I'll publish it in the next version. If the lib was helpful support with a ⭐  :)

**Comment by AbdElRahmanMostafa1** [comment]
> @AbdElRahmanMostafa1 Done merged. I'll publish it in the next version. If the lib was helpful support with a ⭐ :)

Of course will support with a ⭐ @anday013
