### ISSUE TITLE
'focusedPinCodeContainerStyle' does not exist in type 'Theme'

### ISSUE THREAD

**Issue by NhanTruong420** [anday013/react-native-otp-entry#23]
Hey @anday013 i think something when wrong with this property and maybe you has not merged code yet =))
![Screenshot 2023-11-10 at 12 00 32](https://github.com/anday013/react-native-otp-entry/assets/121073662/315a8bc9-d13c-4d17-ae7d-ed4a2404a719)

**Comment by anday013** [comment]
Hey @NhanTruong420 , sorry I was busy this week, so postponed the release. Now it's done, please update to `version 1.3.0` and you should be fine :) Thanks. 


If the lib was helpful, you can support with ⭐ ;)

**Comment by NhanTruong420** [comment]
Thanks for your helping, everything work fine now :) I will give a good review for your tool 🥳
