### ISSUE TITLE
Autofocus when component render

### ISSUE THREAD

**Issue by elsieej** [anday013/react-native-otp-entry#24]
Hi, tks you for creating a great component which custom style on it easily.

It's will better when add autofocus the 1st input when component render, isn't it ?

**Comment by anday013** [comment]
@elsieej Hi, thank you! I think It's already in the codebase:


https://github.com/anday013/react-native-otp-entry/blob/e4a7753691955291f3b6760232c30f4684ac3f15/src/OtpInput/OtpInput.tsx#L77

**Comment by elsieej** [comment]
@anday013,  i was looking for the docs and type declaration but didn't see it, my mistake. So i will close the issues now, tks you very much!
