### ISSUE TITLE
Pasting code into input

### ISSUE THREAD

**Issue by sarahabuteen** [anday013/react-native-otp-entry#30]
I'd like to be able to long-press one of the inputs or the whole component and then press the 'paste' button to paste the OTP that is stored in my clipboard. Is there a way to achieve that currently?

I also suggest adding `textContentType="oneTimeCode"` to the TextInput, it can be used to indicate that a field can be auto-filled by a code arriving in an SMS on iOS.

**Comment by anday013** [comment]
@sarahabuteen Thank you for such nice ideas! Feel free to open a PR and investigate it with me :)

**Comment by Biki-das** [comment]
@anday013 how did you handled pasting could you link me to the code snipped handling the same

**Comment by Biki-das** [comment]
> @Biki-das here setting from the `ref`:
> 
> https://github.com/anday013/react-native-otp-entry/blob/7db6d76c2cea11969438069c21a97f7d74cd1b98/src/OtpInput/useOtpInput.ts#L26

@anday013 😅 could you explain how are you able to retrieve the copied text without using clipboard package and how are you specifically looking for paste events

**Comment by anday013** [comment]
@Biki-das I see what you're asking. Basically, there is no 'paste from clipboard' feature. This function sets the value 'programatically', i.e., you can call `ref.setValue('123456')` and it will be set. So, it does not paste from clipboard rather sets value that is passed as an argument to the function. Hope it's clear now 😅

**Comment by Biki-das** [comment]
@anday013 how you are then observing the paste event like when does this function gets called back appropriately such that

**Comment by anday013** [comment]
@Biki-das I think I did not fully get the question, may ask you to explain again please? :)

P.S. In my example, it calls `handleTextChange` where the state is being modified (by `setText`) with the passed argument, and new value is being set

**Comment by Biki-das** [comment]
> @Biki-das I think I did not fully get the question, may ask you to explain again please? :)
> 
> 
> 
> P.S. In my example, it calls `handleTextChange` where the state is being modified (by `setText`) with the passed argument, and new value is being set 

Like how are you differentiate when a user tries to paste and when trying to fill the inputs one by one.

**Comment by anday013** [comment]
@Biki-das  There is no difference. As I mentioned, there is no pasting from the clipboard. In the current implementation, there is only one possibility to fill out and no way to paste.

There is a possibility kinda "filling all at once" by calling that set function from ref, but as I said, it's just filling all at once, not pasting from clipboard :) I understand It may sound a bit confusing to you, but I am ready to explain, and you can also take advantage of looking at the codebase, as it's not that complicated compared to more sophisticated libraries :)

**Comment by Biki-das** [comment]
thanks @anday013 , i am sharing you a gist sort of a  small implementation of my own  otp component

https://gist.github.com/Biki-das/09385fd18a014904a90ca7a8b15612f4

? how can i do the same sort of functionality.

**Comment by Biki-das** [comment]
@anday013 if the paste button does not appears on long press? how shall a user on phone be able to paste any idea

**Comment by anday013** [comment]
> thanks @anday013 , i am sharing you a gist sort of a small implementation of my own otp component
> 
> https://gist.github.com/Biki-das/09385fd18a014904a90ca7a8b15612f4
> 
> ? how can i do the same sort of functionality.

You do not have pasting functionality either

**Comment by anday013** [comment]
> @anday013 if the paste button does not appears on long press? how shall a user on phone be able to paste any idea

it does not appear because, long press on plain views (as each pin container is a view) does not affect/trigger actual TextInput (as it is small and invisible). It's the actual problem

**Comment by auronvila** [comment]
hey guys I saw the component and I loved the idea it would be great if we could implement the copy paste and the auto fill functionalities lets break these two issues down and brainstorm how can we do it.

**Comment by anday013** [comment]
hey guys, thank you all for the interest. I've created a separate issue #31  to break down this functionality, which was a nice suggestion from @auronvila . I included all the required information; feel free to give it a try and ask any questions you have there.
