### ISSUE TITLE
Implement "Copy/Paste" feature

### ISSUE THREAD

**Issue by anday013** [anday013/react-native-otp-entry#31]
## Feature Description
 Currently, there is a lack of a feature for pasting code from the clipboard for the user.

## Context of issue
The current implementation of the TextInput component is the following: there is a single `<TextInput />` component that is being hidden while the value inputted in it is being displayed inside the separated `<Text />` components, which are the actual "Input cells" that the user sees on the screen. `<TextInput />` mentioned above is focused when `<Text />` (cells) are being tapped. P.S. the tap is handled by `Pressable` that wraps each `Text` component:

https://github.com/anday013/react-native-otp-entry/blob/7db6d76c2cea11969438069c21a97f7d74cd1b98/src/OtpInput/useOtpInput.ts#L10-L16

_Recap:_ There is a single `TextInput` that's hidden and several `Text` components in the form of "cells", where each of the digits of the OTP code is being populated and displayed.

## Issue
The "copy/paste" feature is a built-in feature in `TextInput` component, and in our case, it's been hidden from the user, there is no way for the user to pop up the built-in `TextInput` "text selection menu", which looks like this:
<img width="355" alt="Screenshot 2024-01-06 at 19 39 27" src="https://github.com/anday013/react-native-otp-entry/assets/48630069/fd594e77-137c-498a-b96c-45e3331e0462">

## Possible solutions

**Easy approach:** It is possible to add _context menu_ on long press and add custom options; however, it would kill the native feeling.
+: Easy to implement
-: Not native UX

**Deep approach:** It would be cool to trigger the native "text selection menu", however it probably requires a native piece of code for each platform
+: Fully native UX
-: Requires platform native knowledge to implement 

## TODOs:

- [ ] Paste functionality
- [ ] Copy functionality

# Implementation

## Actual implementation:

The actual implementation was way easier :D I just "streched" the input over the whole container, and now the context menu with copy/past is being triggered when user interacts with the container :)

**Comment by Biki-das** [comment]
@anday013 would you try implementing the same?

**Comment by anday013** [comment]
@Biki-das I am trying to come up with ideas :)

**Comment by anday013** [comment]
@Biki-das I've added some possible ways to implement it, you can take a look

**Comment by anday013** [comment]
@Ozaoujal it's been implemented, please update to the latest version (v1.5.0)  :)
