### ISSUE TITLE
Enabling only number inputs

### ISSUE THREAD

**Issue by erenkulaksiz** [anday013/react-native-otp-entry#41]
Hello,

I am using this library on my new application and i am very happy, tried multiple libraries but this is the one.

But i am having this issue: I only want numeric input.

Of course, i can just put regex and check on every text input.

On emulator, i can use my keyboard and type with non numeric inputs. This is not a big of an issue, but i would like to see `numeric` prop.

**Comment by anday013** [comment]
@erenkulaksiz Hi, I created PR with changes, also exposed the underlying TextInput props so u can set anything u want later. Zaman ayırdığın için teşekkürler :)
