### ISSUE TITLE
Paste functionality is disabled when adding styles

### ISSUE THREAD

**Issue by kamlesh-tp** [anday013/react-native-otp-entry#42]
When we add elevation to pinCodeContainerStyle. The pasting functionality dosen't work

`pinCodeContainerStyle: {
    elevation: 2,
  }`

**Comment by anday013** [comment]
Hi, @kamlesh-tp  thank you for your PR. I've created workaround to modify the `elevation` of underlying textInput. You need to set TextInput `elevation` higher than pinCodeContainer `elevation`. So, here is the example of fix for your case: 

<img width="1300" alt="image" src="https://github.com/anday013/react-native-otp-entry/assets/48630069/3cf1f6f8-e27f-4cbf-9c9a-3589aba7719d">

**Comment by anday013** [comment]
I am closing the issue by merging the PR. Tomorrow, I'll make the release, so you can upgrade the package and take a look. If it won't work, feel free to reopen the issue :)
