### ISSUE TITLE
Contribute Your Creativity: Custom Styles for "react-native-otp-entry"

### ISSUE THREAD

**Issue by anday013** [anday013/react-native-otp-entry#47]
# Hello Community 👋

I'm inviting you to contribute custom styles to enhance react-native-otp-entry showcase. Your creativity will not only improve the library but also inspire other users of the library.

## Share Your Work

**Upload Video or Screenshot:** Provide a video or screenshot showcasing your custom styles.
**Share Code (Optional yet Preferable):** Optionally, share your style code, preferably in a Snack Expo project.

Snack Expo: https://snack.expo.dev/@anday013/demo-react-native-otp-entry

### Examples:

Dark Mode theme 🌑
Material Design-inspired styles 🎨
Minimalistic styles 🌱

**or any other custom ones...**

Thank you for your contributions! 🎉

**Comment by carl0smat3us** [comment]
A great idea

**Comment by anday013** [comment]
Moved to Discussions https://github.com/anday013/react-native-otp-entry/discussions/64
