### ISSUE TITLE
A way to disable cursor/caret inside the input

### ISSUE THREAD

**Issue by martenjurgens** [anday013/react-native-otp-entry#5]
First of all, thank you for this neat little component.

I couldn't seem to find a way to disable the blinking cursor/caret inside the input. Would be nice to have an option to disable that.

Thank you.

**Comment by anday013** [comment]
Hey @martenjurgens , thank you for the idea. I'll include it for you in the next version 🙂

**Comment by anday013** [comment]
@martenjurgens Done. Please try to update to the latest version 🙂
