### ISSUE TITLE
Cannot focus on a previous digit input

### ISSUE THREAD

**Issue by coder966** [anday013/react-native-otp-entry#51]
**Describe the bug**
Cannot focus on a previous digit input

**To Reproduce**
1. Fill one or more digits
2. Click on a previous digit box
3. Error: Focus stays on the same last input not the one pressed.
4. Error: Android text selector (or whatever that is) appears (less important) 

**Expected behavior**
1. Should bring focus to the pressed digit box.
2. Should never show the text selector.

**Screenshots**
I pressed the first box. 
![image](https://github.com/anday013/react-native-otp-entry/assets/11215861/f902d4ad-34a4-4ea9-8617-c664ff5e0ebe)

**Environment (please complete the following information):**
 - OS: Linux 6.8
 - Device OS: Android
 - Device version: Android 14
 - Library version: 1.6.1

**Additional context**

**Comment by coder966** [comment]
That is okay with me. But what about the second point (the caret)?

 I created a PR to hide the caret of the hidden input. See that green bubble which indicates there's a text input but it is actually hidden.
 
 Thank you for your amazing component.

**Comment by anday013** [comment]
@coder966 I left a comment, please, take a look
