### ISSUE TITLE
Focusing on fully filled input should have a focused affordance

### ISSUE THREAD

**Issue by rob-pathway** [anday013/react-native-otp-entry#53]
When the OTP is fully filled and pressed (for editing), I think the input should show that it's focused somehow.

Proposal would be to focus (but persist) the last digit/character.

Thanks for this component!

**Comment by anday013** [comment]
@rob-pathway Thank you for the proposal. I'll try to improve this aspect

**Comment by rob-pathway** [comment]
Happy to submit a PR if you’d like!

**Comment by anday013** [comment]
@rob-pathway sure!

**Comment by mrEuler** [comment]
@anday013 @rob-pathway just quick question, as I want to use this package. Will this PR be merged soon? :)

**Comment by anday013** [comment]
@mrEuler @rob-pathway sry for delay. I'll make it available this week, thanks :)

**Comment by anday013** [comment]
Merged #56

**Comment by mrEuler** [comment]
@anday013 will test now, thank you man!

**Comment by mrEuler** [comment]
@anday013 when could you publish new version?

**Comment by anday013** [comment]
@mrEuler I want to merge the open PRs, and go for major release. I'll try to do it later today

**Comment by mrEuler** [comment]
@anday013 that would be awesome! Thanks again!

**Comment by anday013** [comment]
@mrEuler A new version (1.7.0) is available with changes you need ✅ 🎉

**Comment by rob-pathway** [comment]
@anday013 Thanks for adding tests. Looking good!
