### ISSUE TITLE
Cannot Reduce Gap Between Inputs

### ISSUE THREAD

**Issue by rick427** [anday013/react-native-otp-entry#57]
**Describe the bug**
Setting a gap or margin on the containerStyle or pinCodeContainerStyle doesn't work. 

**To Reproduce**

**Expected behavior**
The spacing or gap between input elements should change based on the spacing provided

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac
 - Device OS: Android
 - Device version: react native 0.73.7
 - Library version: 1.6.1

**Additional context**

**Comment by anday013** [comment]
@rick427 Hi, thank you for bringing up this issue! I'll fix it asap. As a temporary workaround you can use this combination if props to deal with it:

**Comment by rick427** [comment]
Thanks

**Comment by anday013** [comment]
@rick427 Welcome! Could u please take a look at the PR I created #58 . The default `width`  is `100%` (I do not want to break the default behaviour for prev users), when you're setting `gap`, u need to set `width` to `undefined` or `'auto'`. Is it acceptable solution, WDYT?
![image](https://github.com/anday013/react-native-otp-entry/assets/48630069/53daab2c-9c84-4cc3-8fa1-0710a1551845)

**Comment by rick427** [comment]
Looks good
