### ISSUE TITLE
Keyboard Does Not Dismiss After All Values Are Filled (IOS)

### ISSUE THREAD

**Issue by rick427** [anday013/react-native-otp-entry#59]
**Describe the bug**
So I discovered this after deploying my app to the play store and app store respectively. On android the keyboard remains visible even after all inputs are filled but there's a return button to dismiss it so I don't really have a problem here.. However, on IOS after filling all inputs the keyboard remains active with no way to dismiss it.

**To Reproduce**

**Expected behavior**
The keyboard should dismiss automatically after filling all inputs or it can remain active but there should to be a way to dismiss it after all inputs are checked.

**Screenshots**
![WhatsApp Image 2024-05-27 at 11 43 35 AM](https://github.com/anday013/react-native-otp-entry/assets/44168932/da9e0438-7fe0-4499-8680-9b14f7350918)

**Environment (please complete the following information):**
 - OS: Mac
 - Device OS: IOS
 - Device version: 0.73.7
 - Library version: 1.6.1

**Additional context**

**Comment by anday013** [comment]
Hi @rick427 , thank you. I've raised a PR (#60 ) to solve this issue. As a temporary solution, you can call `blur()` from input ref inside `onFilled()` callback

**Comment by rick427** [comment]
Hi, I don't quite follow. `blur()` is not exposed from the library's ref, so where am i getting it from ?

**Comment by anday013** [comment]
Oh, sorry, I thought I had exposed underlying TextInput `ref` for external use. Actually, that's a fair point, I think it'd better to expose it for more flexibility. WDYT?

**Comment by rick427** [comment]
Yes

**Comment by rick427** [comment]
Hi what's the update on this ? has it been merged ? it's currently affecting our live app for ios users

**Comment by anday013** [comment]
I see! I am creating a new version with fix. It will be available in the upcoming hours

**Comment by rick427** [comment]
Much appreciated. Will be on the lookout

**Comment by anday013** [comment]
@rick427 A new version (1.7.0) is available with changes you need ✅ 🎉

**Comment by akuul** [comment]
@anday013 Is there a reason why you didn't expose blur on ref ? I recently had a use case where blurOnFilled wasn't sufficient. Just wondering if I'm missing something for the blur() not being exposed

**Comment by anday013** [comment]
@akuul Have you tried to set ref on OtpInput and try to call .current.blur() funciton on it?

**Comment by akuul** [comment]
I did, it is not exposed nor typed. I saw you did PR to add a prop, but didn't expose blur() seems to remain internal only
https://github.com/anday013/react-native-otp-entry/blob/main/src/OtpInput/OtpInput.types.ts#L23
