### ISSUE TITLE
`autoFocus` on Huawei devices pops out an `alpha` keyboard even it is set to 'numeric' type

### ISSUE THREAD

**Issue by amiruddin-roslam** [anday013/react-native-otp-entry#66]
**Describe the bug**
Was testing on Huawei devices and found out that when enabled the `autoFocus`, keyboard present as and `alpha` type even it is set as `numeric`

**To Reproduce**
1. set `type` props to `numeric`
2. Test on Huawei devices

**Expected behavior**
Should follow as Android and iOS

**Environment (please complete the following information):**
 - OS: EMUI 13
 - Device OS: EMUI 13.0.0
 - Device version: 13.0.0
 - Library version: 1.7.1

**Comment by anday013** [comment]
Hi @amiruddin-roslam sorry to hear that. As I do not have an Huawei phone to test, I'll ask you to help me with debugging. Firstly, setting `type` prop to `alpha` does not change keyboard, rather, it prevents the unexpected values from be inserted. Nevertheless, I found a source with similar issue on Android (https://github.com/facebook/react-native/issues/15346#issuecomment-370195817). Can you try to set `autoCapitalize="none"`

**Comment by anday013** [comment]
Closing this ticket due to inactivity. Also, there are ongoing changes on type prop: https://github.com/anday013/react-native-otp-entry/pull/68
