### ISSUE TITLE
Enable test support

### ISSUE THREAD

**Issue by franconob** [anday013/react-native-otp-entry#7]
Hello there! First of all, great work on this! I was wondering if you are planning to add some `testID` attributes to be able to locate input elements when running unit/e2e tests.

Thanks!

**Comment by anday013** [comment]
Hi, @franconob ! Thank you for bringing this topic up. I'll address your request at the nearest time :)

**Comment by anday013** [comment]
@franconob , I've included unit tests and also `testID`s as you requested. Please take a look at the PR to see if there any missing `testID` that you need 🙂
