### ISSUE TITLE
Breaks android tv's directional focusing.

### ISSUE THREAD

**Issue by evoactivity** [anday013/react-native-otp-entry#71]
**Describe the bug**
Android tv makes views focusable using the direction keys, when adding this component the view becomes entirely unfocasable, it makes it's sibling elements also become unfocusable.

If the component is moved out of the containing view then the sibling elements become focusable again, but it's impossible to focus onto the otp input, which is why my example has a pressable which when focused moves focus to the input manually.

**To Reproduce**
Use the react-native-tvos project 

Create a screen something like

```jsx
const pinEntry = useRef<OtpInputRef>(null);

<TVFocusGuideView
  focusable={true}
  autoFocus={true}
  hasTVPreferredFocus={true}
  style={{ flex: 1, height: '100%', width: '100%', borderWidth: 1, borderColor: 'black' }}
>
  <Pressable
    onPress={() => {
      pinEntry.current?.focus();
    }}
    onFocus={() => {
      pinEntry.current?.focus();
    }}
  >
    {({ focused }) => (
      <View style={{ width: 200, height: 200, backgroundColor: focused ? 'blue' : 'red' }}>
        <Text>Enter PIN</Text>
      </View>
    )}
  </Pressable>
  <OtpInput
    type="numeric"
    ref={pinEntry}
    numberOfDigits={4}
    onTextChange={(text) => console.log(text)}
    theme={{
      containerStyle: {
        position: 'relative',
        display: 'flex',
        width: 200,
        height: 200,
        backgroundColor: 'red',
      },
    }}
  />
</TVFocusGuideView>
```

Try to navigate with the arrow keys.

**Expected behavior**
Normal focus behaviours remain unaffected when using this component

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS
 - Device OS: Android TV
 - Device version: n/a (tested on emulator)
 - Library version: 1.7.1

**Additional context**

**Comment by evoactivity** [comment]
I worked around this by wrapping the OTP input in a pressable and then focusing on the input when pressed.

**Comment by anday013** [comment]
https://github.com/anday013/react-native-otp-entry/pull/73#issuecomment-2374609866
