### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by sombek** [anday013/react-native-otp-entry#76]
is there RTL Support?

**Comment by anday013** [comment]
i have not tested it. If you have such a use case, can u test and let us know?

**Comment by anday013** [comment]
if it lacks and you need it, we can try to add :) @sombek

**Comment by anday013** [comment]
any updates here? @sombek

**Comment by maxlar01** [comment]
In the theme prop, you can pass flex direction as row-reverse to fix direction in RTL:
`theme={{
        containerStyle: {
          flexDirection: isRTL ? 'row-reverse' : 'row',
        },
}}`
@sombek

**Comment by anday013** [comment]
Thank you @maxlar01  Closing the issue, feel free to reopen if you have something
