### ISSUE TITLE
May I know is it to possible to fix a typo in the middle?

### ISSUE THREAD

**Issue by danielchan303** [anday013/react-native-otp-entry#78]
**Is your feature request related to a problem? Please describe.**
Currently, if I can a typo, I cannot just focus and change that char but can only delete from the end and type it again.

**Describe the solution you'd like**
I would like to be able select a char in the middle and fix it from there.

**Comment by anday013** [comment]
This feature is not presented currently. You can see more details here https://github.com/anday013/react-native-otp-entry/issues/65

**Comment by anday013** [comment]
@danielchan303 Any ideas or suggestions here? Should i close this issue? :)

**Comment by anday013** [comment]
Closing the issue feel free to reopen, if there is something
