### ISSUE TITLE
Placeholder not showing. When disabled prop is true, the value does not show, it just shows blank

### ISSUE THREAD

**Issue by jgudo** [anday013/react-native-otp-entry#82]
I wonder why the placeholder is not showing in the ```textInputProps``` props
```
<OtpInput 
    numberOfDigits={5}
    onTextChange={onReadingChange}
    textInputProps={{ 
           placeholder: '0', 
           placeholderTextColor: '#1a1a1a', 
           readOnly: filters.viewMode === 'read' 
    }}
    theme={readingInputStyle as OtpInputProps['theme']}
    type="numeric"
    blurOnFilled={true}
    ref={readingValInputRef}
 />
 ```
 Moreover, when disabled prop is true, the value do not show and just shows blank so instead of adding ```disabled``` prop, I just use the ```readOnly``` prop in the ```textInputProps```

**Comment by anday013** [comment]
@jgudo Hey, nice catch of the placeholder. I have not considered it before. It needs to be implemented.

To disable the input properly use `disabled` prop in the root props: ex.:
<OtpInput
    disabled
    ...
/>

**Comment by jgudo** [comment]
> @jgudo Hey, nice catch of the placeholder. I have not considered it before. It needs to be implemented.
> 
> To disable the input properly use `disabled` prop in the root props: ex.: <OtpInput disabled ... />

If I use the ```disabled``` prop, it just shows empty/blank fields. Is that the default behavior? So instead I use the ```readOnly``` prop in the ```textInputProps```

**Comment by anday013** [comment]
@jgudo I've tried `readOnly`, but it still displays a blinking cursor. However, `disabled` removes this issue

**Comment by mario-isca-TW** [comment]
Hello everyone, is there any update regarding the placeholder? I am using the library, but unfortunately I realized that it's not possible to add a placeholder, and I have read this issue. Thank you!

**Comment by anday013** [comment]
I'll try to add this feature on weekends

**Comment by mario-isca-TW** [comment]
Hi @anday013 ! Any updates regarding the placeholder?

**Comment by anday013** [comment]
Implemented. Left to do proper testing and write unit tests

**Comment by mario-isca-TW** [comment]
@anday013 

Hi! When do you plan to merge the feature? Thanks :D

**Comment by anday013** [comment]
Done. Please update to 1.8.0
