### ISSUE TITLE
Placeholder does not seem to work

### ISSUE THREAD

**Issue by silencer07** [anday013/react-native-otp-entry#87]
Sample code

<OtpInput
  numberOfDigits={6}
  theme={{
    placeholderTextStyle: {
      color: 'black',
      fontFamily: 'Geist',
      fontSize: bonnyFont.size.h3,
      fontWeight: getFontWeights().bold as any,
      borderWidth: 1,
      borderColor: 'red'
    }
  }}
  placeholder="0"
/>

<img width="1224" alt="Screenshot 2024-12-09 at 3 39 20 PM" src="https://github.com/user-attachments/assets/c92967f1-c141-4fb2-8a97-f7b781166457">

**Comment by mario-isca-TW** [comment]
@anday013 

Thank you so much for your prompt merge and your availability!
Unfortunately, the placeholder isn't working as expected.
I expect each input to have an independent placeholder.
(For example, if I set the placeholder as "-", I expect all the OTP inputs to display "-").
I also noticed that when I focus on one input, all the other placeholders disappear.
Thank you!

**Comment by anday013** [comment]
Okay, I see your problems. It seems like, I made it not so intuitive. The current logic:

1. Each character of your "placeholder" prop gets populated to the input. Ex. if you want it to be "000000", you need to explicitly write 6 times "0", instead of just a single "0".
2. The other logic is that, currently, the placeholder is disappearing when the input gets focused. Should I change it to disappear when user starts typing?

Lmk, if I should change these "logics"

**Comment by silencer07** [comment]
> Okay, I see your problems. It seems like, I made it not so intuitive. The current logic:
> 
>     1. Each character of your "placeholder" prop gets populated to the input. Ex. if you want it to be "000000", you need to explicitly write 6 times "0", instead of just a single "0". ("------" for your case @mario-isca-TW )
> 
>     2. The other logic is that, currently, the placeholder is disappearing when the input gets focused. Should I change it to disappear when user starts typing?
> 
> 
> Lmk, if I should change these "logics"

I agree to all of this. especially the #2 because by default the otp in put is focused immediately anyway

**Comment by mario-isca-TW** [comment]
@anday013 

I think the correct behavior is that each input should be independent and not treated as part of a group.
If I focus on the first input, only the placeholder of the first input should disappear, not the placeholders of all the other inputs. Thank you so much for your help!

**Comment by mario-isca-TW** [comment]
Hi @anday013 , any updates on the placeholder fix? Thanks!

**Comment by anday013** [comment]
In the meantime, you can also try to take a look. Here is the implementation of the placeholder #86

**Comment by anday013** [comment]
All your concerns and improvements have been addressed. Please upgrade to 1.8.2 version. cc @mario-isca-TW  @silencer07
