### ISSUE TITLE
trying to use ref

### ISSUE THREAD

**Issue by vksgautam1986** [anday013/react-native-otp-entry#90]
**Describe the bug**
i am trying to use ref to setvalue but its giving null. otpInputRef.current its giving null

**Expected behavior**
can use ref to setvalue 

**Environment (please complete the following information):**
 - OS: mac os
 - Device OS: IOS
 - Device version:17.6
 - Library version: latest

Code `
const OTPVerificationModal =forwardRef((props, ref) => {
    const { showOtpVerificationModal, hideOtpVerificationModal, onChangeTextOtp, onSubmitOtp }=props;
    const otpInputRef = useRef<OtpInputRef>(null); // Explicitly type the ref

    // Expose methods through ref
    React.useImperativeHandle(ref, () => ({
      setValueOtp: (newValue: string) => {
        console.log("otpInputRefotpInputRef ", otpInputRef)
        otpInputRef.current?.setValue('123456')
      },
      // Add other methods you want to expose
    }));
    
    return (
        <Modal statusBarTranslucent={true} animationType="slide" transparent={true} visible={showOtpVerificationModal} onRequestClose={() => { }} style={styles.centeredView}>
            <View style={styles.centeredView}>
                <View style={styles.parentView}>
                    <View style={styles.bodyView}>
                        <Text style={[styles.text, styles.margin]}>{i18next.t('otpVerification')}</Text>
                        <TouchableOpacity
                            style={[styles.cross, styles.margin]}
                            onPress={hideOtpVerificationModal}>
                            <Image
                                style={{
                                    width: moderateScale(18),
                                    height: moderateScale(18),
                                    tintColor: colors.gray,
                                }}
                                source={Images.cross}
                            />
                        </TouchableOpacity>
                    </View>
                    <Text style={{ fontWeight: '600', color: colors.gray }}>{i18next.t('enterOTP')}</Text>
                    <View style={styles.base}>                       
                        <View style={{ flexDirection: 'row', justifyContent: 'space-evenly', marginTop: 5 }}>                            
                            <OtpInput ref={otpInputRef} theme={{pinCodeContainerStyle:{backgroundColor:'#F1F1F1'}, focusedPinCodeContainerStyle:{borderColor:colors.appColor}}}type="numeric" numberOfDigits={6} onTextChange={(text) => onChangeTextOtp(text)} />
                        </View>
                        <View >
                            <TouchableOpacity style={[styles.button,{marginTop:30}]} onPress={onSubmitOtp}>
                                <Text style={styles.laterStyle}>{i18next.t('verifyProceed')}</Text>
                            </TouchableOpacity>
                        </View>
                    </View>                   
                </View>
            </View>
        </Modal>
    )
})

`

**Comment by vksgautam1986** [comment]
![Screenshot 2024-12-27 at 1 33 18 PM](https://github.com/user-attachments/assets/35be7d5f-b874-4725-b25e-74b2ff150cfa)

**Comment by vksgautam1986** [comment]
now i defined this modal inside the main component .
this is how it shows and if if i try to access its showing null
 console.log("this.otpRef.current", this.otpRef)
    console.log( this.otpRef.current)
![Screenshot 2024-12-27 at 2 43 00 PM](https://github.com/user-attachments/assets/fb71a86b-df0f-42db-9d5d-1f9455419ccb)

**Comment by anday013** [comment]
From the first sight, it makes me think that the issue is in the initialization time of the component. As the modal is not rendered straight away on the screen, setting reference skips first renders. So it becomes available in the later renders

**Comment by vksgautam1986** [comment]
ya that is the issue . thanks i have just added the timeout for it.
